apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-userservice
  labels:
    app: cm-userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm-userservice
  template:
    metadata:
      labels:
        app: cm-userservice
    spec:
      containers:
      - name: cm-userservice
        image: scionticdx/userservice