apiVersion: v1
kind: Service
metadata:
  name: campusservice
  labels:
    app: campusservice
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: campusservice