apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-authservice
  labels:
    app: cm-authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm-authservice
  template:
    metadata:
      labels:
        app: cm-authservice
    spec:
      containers:
      - name: cm-authservice
        image: scionticdx/authservice