apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cm
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    # traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
  - http:
      paths:
      - path: /Campus
        pathType: Prefix
        backend:
          service:
            name: cm-campusservice
            port:
              number: 80

  - http:
      paths:
      - path: /Authorization
        pathType: Prefix
        backend:
          service:
            name: cm-authservice
            port:
              number: 80


  - http:
      paths:
      - path: /Company
        pathType: Prefix
        backend:
          service:
            name: cm-companyservice
            port:
              number: 80
  - http:
      paths:
      - path: /CampusXCompany
        pathType: Prefix
        backend:
          service:
            name: cm-campusxcompanyservice
            port:
              number: 80
  - http:
      paths:
      - path: /CampusXCompanyXUser
        pathType: Prefix
        backend:
          service:
            name: cm-campusxcompanyxuserservice
            port:
              number: 80

  - http:
      paths:
      - path: /User
        pathType: Prefix
        backend:
          service:
            name: cm-userservice
            port:
              number: 80
  - http:
      paths:
      - path: /Visitor
        pathType: Prefix
        backend:
          service:
            name: cm-visitorservice
            port:
              number: 80
