apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-campusxcompanyservice
  labels:
    app: cm-campusxcompanyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm-campusxcompanyservice
  template:
    metadata:
      labels:
        app: cm-campusxcompanyservice
    spec:
      containers:
      - name: cm-campusxcompanyservice
        image: scionticdx/campusxcompanyservice