apiVersion: v1
kind: Service
metadata:
  name: cm-campusxcompanyservice
  labels:
    app: cm
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cm