apiVersion: v1
kind: Service
metadata:
  name: cm-campusxcompanyxuserservice
  labels:
    app: cm-campusxcompanyxuserservice
spec:
  ports:
  - port: 80
  selector:
    app: cm-campusxcompanyxuserservice