apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-visitorservice
  labels:
    app: cm-visitorservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm-visitorservice
  template:
    metadata:
      labels:
        app: cm-visitorservice
    spec:
      containers:
      - name: cm-visitorservice
        image: scionticdx/visitorservice