apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-campusservice
  labels:
    app: cm-campusservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm-campusservice
  template:
    metadata:
      labels:
        app: cm-campusservice
    spec:
      containers:
      - name: cm-campusservice
        image: scionticdx/campusservice